// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltidnqrtuinpbclaoznx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0aWRucXJ0dWlucGJjbGFvem54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MTA1MDksImV4cCI6MjA2OTA4NjUwOX0.YIkGEQwj6nOWZDaHxWPDHCmANxST1Yc7bmXWAkomZ7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});